name: Sync Gitee
on:
  push:
  pull_request_target:
    branches: [main]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Single repo mirror
      uses: mouse040429/keylol-chinaplay-table@main
      with:
        src: github/mouse040429
        dst: gitee/mouse040429
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "keylol-chinaplay-table"
